"use client";
import "@rainbow-me/rainbowkit/styles.css";
import "bootstrap/dist/css/bootstrap.css";
import "../styles/globals.css";
import { spaceGrotesk } from "../utils/spaceGroteskFontFamily";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { WagmiProvider } from "wagmi";
import { arbitrum, arbitrumSepolia } from "wagmi/chains";
import { getDefaultConfig, RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { ReactNode } from "react";

const config = getDefaultConfig({
  appName: "RainbowKit App",
  projectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_ID as string,
  chains: [
    arbitrum,
    ...(process.env.NEXT_PUBLIC_ENABLE_TESTNETS === "true" ? [arbitrumSepolia] : []),
  ],
  ssr: true,
});

const client = new QueryClient();

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en" className={spaceGrotesk.className}>
      <head>
        <title>App Name</title>
        <meta content="Generated by Primarch Dev" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </head>
      <body>
        <WagmiProvider config={config}>
          <QueryClientProvider client={client}>
            <RainbowKitProvider initialChain={arbitrum}>{children}</RainbowKitProvider>
          </QueryClientProvider>
        </WagmiProvider>
      </body>
    </html>
  );
};

export default Layout;
